name: Rust - Cargo Build, Test & Clippy

on:
  push:
    branches: "*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  BINARYEN_VERSION: 124
  BUN_VERSION: "v1.1.43"
  ASSEMBLYSCRIPT_VERSION: "0.27.27"
  RUST_CHANNEL: "nightly"

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit --version
      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure

  build_test:
    needs: pre-commit-hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update rustup
        run: rustup update ${RUST_CHANNEL} && rustup default ${RUST_CHANNEL}
      - name: Install wasm & wasip1 as a rust target
        run: rustup target add wasm32-unknown-unknown wasm32-wasip1
        shell: bash
      - name: Install Binaryen
        run: |
          mkdir $HOME/binaryen
          wget https://github.com/WebAssembly/binaryen/releases/download/version_${BINARYEN_VERSION}/binaryen-version_${BINARYEN_VERSION}-x86_64-linux.tar.gz -O $HOME/binaryen.tar.gz
          tar -xzvf $HOME/binaryen.tar.gz --directory $HOME/binaryen --strip-components=1
          echo "$HOME/binaryen/bin" >> $GITHUB_PATH
      - name: Verify Binaryen installation
        run: wasm-merge --version
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.1.5
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash -s "bun-${BUN_VERSION}"
      - name: Verify Bun installation
        run: ~/.bun/bin/bun --version
      - name: Install Assemblyscript compiler
        run: ~/.bun/bin/bun install assemblyscript@${ASSEMBLYSCRIPT_VERSION}/asc
      - name: Build all targets with all features
        run: cargo build
        shell: bash
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Test with latest nextest release
        run: cargo nextest run --all-features

  clippy_check:
    needs: pre-commit-hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update rustup
        run: rustup update ${RUST_CHANNEL} && rustup default ${RUST_CHANNEL}
      - name: Install clippy
        run: rustup component add clippy
      - name: Install wasm & wasip1 as a rust target
        run: rustup target add wasm32-unknown-unknown wasm32-wasip1
        shell: bash
      - name: Lint (clippy)
        run: cargo clippy --all-features --all-targets
        shell: bash
